config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, only: [:new]
    resources :friendships, only: [:create]
    delete "/friendships", action: "destroy", controller: "friendships"
  end

  resources :tags, only: [:create]

  resources :secrets, except: [:new]

  resource :session, :only => [:create, :destroy, :new]

  root :to => "users#show"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :out_friend_id, :in_friend_id

  validates :out_friend_id, :in_friend_id, presence: true
  validates :out_friend_id, uniqueness: { scope: :in_friend_id }

  belongs_to :out_friend,
  class_name: "User",
  foreign_key: :out_friend_id,
  primary_key: :id

  belongs_to :in_friend,
  class_name: "User",
  foreign_key: :in_friend_id,
  primary_key: :id


  def self.can_friend?(out_friend_id, in_friend_id)
    !Friendship.exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id)
  end


  def self.can_unfriend?(out_friend_id, in_friend_id)
     Friendship.exists?(out_friend_id: out_friend_id, in_friend_id: in_friend_id)
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title, :tag_ids

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  validates :author_id, :recipient_id, :title, :presence => true
  validates :title, length: { minimum: 2 }

  has_many :secret_taggings,
  class_name: "SecretTagging",
  foreign_key: :secret_id,
  primary_key: :id

  has_many :tags,
  through: :secret_taggings,
  source: :tag

end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id

  validates :secret_id, :tag_id, presence: true

  belongs_to :secret,
  class_name: "Secret",
  foreign_key: :secret_id,
  primary_key: :id

  belongs_to :tag,
  class_name: "Tag",
  foreign_key: :tag_id,
  primary_key: :id

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :creator_id

  validates :name, presence: true
  validates :name, uniqueness: true

  belongs_to :creator,
  class_name: "User",
  foreign_key: :creator_id,
  primary_key: :id

  has_many :secret_taggings,
  class_name: "SecretTagging",
  foreign_key: :tag_id,
  primary_key: :id

  has_many :secrets,
  through: :secret_taggings,
  source: :secret

  has_one :creator,
  through: :secret_taggings,
  source: :creator

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many :friendships,
  class_name: "Friendship",
  foreign_key: :in_friend_id,
  primary_key: :id

  has_many :friends,
  through: :friendships,
  source: :out_friend


  has_many :tags,
  class_name: 'Tag',
  foreign_key: :creator_id,
  primary_key: :id


  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def new
  end

  def create
    @friendship = current_user.friendships.new({out_friend_id: params[:user_id]})

    sleep(2)

    if @friendship.save
      redirect_to :back
    else
      flash[:errors] = @friendship.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @friendship = Friendship.where("in_friend_id = ? AND out_friend_id = ?", current_user.id, params[:user_id])

    sleep(2)

    if @friendship.first.destroy
      head :ok
    end
  end

end

app/controllers/secret_taggings_controller.rb
class SecretTaggingsController < ApplicationController
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

  def new
  end

  def create
    @secret = current_user.authored_secrets.new(params[:secret])
    @secret.tag_ids = params[:secret][:tag_ids]

    if @secret.save
      render partial: "secrets/secret", locals: {secret: @secret}
    else
      flash.now[:error] = @secret.errors.full_messages
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(params[:tag])
    if @tag.save
      head :ok
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secret_taggings_helper.rb
module SecretTaggingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<form action="<%= user_friendships_url(user) %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="submit" value="Friend!">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<h2> New Secret </h2>

<form id="new-secret-form" action="<%= secrets_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<% form_authenticity_token %> ">

   <label>Title
     <input type="text" name="secret[title]" value="">
   </label>
   <br>

   <input type="hidden" name="secret[recipient_id]" value="<%= params[:id] %>">

   Tag With
   <section id="tag-selection">
     <%#= render partial: "tags/choose_tag" %>
   </section>

   <br>

   <input type="submit" value="Submit">
</form>

   <button id="add-tag">Add Another Tag</button>

app/views/secrets/_secret.html.erb
<li><%= secret.title %></li>
<ul>
  <% secret.tags.each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
</ul>

app/views/secrets/new.html.erb
<form action="<%= secrets_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<% form_authenticity_token %> ">

   <label>Title
     <input type="text" name="secret[title]">
   </label>
   <br>

   <input type="hidden" name="secret[recipient_id]" value="<%= params[:user_id] %>">

   <input type="submit" value="Submit">
</form>

app/views/tags/_choose_tag.html.erb
<select name="secret[tag_ids][]">
<% Tag.all.each do |tag| %>

  <option value="<%= tag.id %>">
    <%= tag.name %>
  </option>

<% end %>
</select>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<h1> Users </h1>

<script type="text/javascript">

function toggleFriendButtons ($el) {

  $el.toggleClass("friend-buttons can-unfriend");
  $el.toggleClass("friend-buttons can-friend");

}

  $(document).ready(function() {
    $('#users').on("click", "input[type=submit]", function(event){

      event.preventDefault();

      var $button = $(this);
      var formData = $button.serialize();
      var userId = parseInt($button.attr("data"));

      var $containingLi = $button.closest('li');

      $button.attr("disabled", "");

      if ($button.is(".friend")) {

        $button.attr("value", "Friending...");

        $.ajax({
          url: "/users/" + userId + "/friendships",
          type: "POST",
          data: formData,
          success: function() {
            toggleFriendButtons($containingLi);
          }
        });
        } else if ($button.is(".unfriend")) {
          $button.attr("value", "Unfriending...");

          $.ajax({
            url: "/users/" + userId + "/friendships",
            type: "DELETE",
            data: formData,
            success: function() {
              toggleFriendButtons($containingLi);
            }
          });
        }

    });
  });

</script>

<style>
  li.friend-buttons.can-friend input.unfriend {
    display: none;
  }

  li.friend-buttons.can-unfriend input.friend {
    display: none;
  }
</style>

<ul id="users">
  <% @users.each do |user| %>

  <% if current_user.id != user.id %>

  <li class="friend-buttons <%= Friendship.can_unfriend?(user.id, current_user.id) ? 'can-unfriend' : 'can-friend' %>">

      <%= link_to user.username, user_url(user) %>

      <%= button_to "Friend!", user_friendships_url(user), class: "friend", data: user.id %>

      <%= button_to "Unfriend! :(", user_friendships_url(user), method: :delete, class: "unfriend", data: user.id %>

  </li>
  <br>

   <% end %>
  <% end %>

</ul>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<script>

  $(document).ready(function () {
    $('#new-secret-form').on("submit", function (event) {

      event.preventDefault();
      var formData = $(this).serialize();
      var formObject = $(this).serializeJSON();
      var form = $(this);

      $.ajax({

        url: "<%= secrets_url %>",
        type: "POST",
        data: formData,
        success: function(data) {
          form[0].reset();
          $('#secrets').prepend(data);
        }

      });

    });

    // var selectBox = $('#tag-selection').html();

    var tags = JSON.parse($("#bootstrapped_tags_json").html()).tags;
    var templateCode = $("#tag_select_template").html();
    var templateFn = _.template(templateCode);
    var renderedContent = templateFn({
      tags: tags
    });

    $("#tag-selection").html(renderedContent);


    $('#add-tag').on('click', function(event){

      $("#tag-selection").append(renderedContent);

    });

  });

</script>

<script type="application/json" id="bootstrapped_tags_json">
  { "tags": <%= Tag.all.to_json.html_safe %> }
</script>

<script type="text/template" id="tag_select_template">
  <select name="secret[tag_ids][]">
  <option value=""></option>
    <%% _(tags).each(function (tag)  { %>

      <option value="<%%=tag.id%>">

        <%%=tag.name%>

      </option>

    <%% }); %>
  </select>
</script>

<h1><%= @user.username %></h1>

<%= render 'secrets/form' %>

<h2>Secrets</h2>
<ul id="secrets">
  <% @user.received_secrets.each do |secret| %>
    <%= render partial: "secrets/secret", locals: {secret: secret} %>
  <% end %>
</ul>